title: Modding Minecraft with Python
hero_image: images/banner.png
description: Navigate the world of Minecraft Pi, learn to create with code and blow things up with TNT
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: games
technologies: python
site_areas: jam
hardware: ''
software: python
version: 4
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: Enter the Minecraft world
- title: Controlling Minecraft with Python
- title: TNT