---
title: Minecraft TNT
hero_image: images/banner.png
description: Minecraft Pi की दुनिया को नेविगेट करें, कोड के साथ निर्माण करना सीखें और टीएनटी का उपयोग कर चीजों को उड़ाएं
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: परिचय
  - 
    title: Enter the Minecraft world
  - 
    title: Controlling Minecraft with Python
  - 
    title: TNT
