---
title: Minecraft（マインクラフト） TNT
hero_image: images/banner.png
description: Minecraft Piのワールドを探検し、TNTブロックで爆発させるプログラムの作成方法を学びましょう
listed: false
copyedit: false
version: 3
last_tested: 2018-11-21
steps:
  - 
    title: はじめに
  - 
    title: Minecraftのワールドに入る
  - 
    title: PythonでMinecraftを制御する
  - 
    title: TNT
