---
title: Minecraft TNT
hero_image: images/banner.png
description: Навигирайте в света на Minecraft Pi, научете се да създавате и да взривявате неща с TNT чрез код
listed: false
copyedit: false
version: 4.1
last_tested: 21.11.2018
steps:
  - 
    title: Въведение
  - 
    title: Влез в Minecraft света
  - 
    title: Команди в Minecraft с Python
  - 
    title: TNT
