---
title: Minecraft TNT
hero_image: images/banner.png
description: حرکت در دنیای Minecraft Pi، ساختن با کد را یاد بگیرید و با TNT چیزهای مختلف را منفجر کنید
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: مقدمه
  - 
    title: Enter the Minecraft world
  - 
    title: Controlling Minecraft with Python
  - 
    title: TNT
