---
title: Minecraft mit Python verändern
hero_image: images/banner.png
description: Navigiere in der Welt von Minecraft Pi, lerne, mit Code etwas zu erschaffen und dann etwas mit TNT in die Luft zu jagen
listed: false
copyedit: false
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Einleitung
  - 
    title: Was du brauchen wirst
  - 
    title: Komme in die Minecraft-Welt
  - 
    title: Minecraft mit Python steuern
