---
title: Minecraft és Python
hero_image: images / banner.png
description: Utazz a Minecraft Pi világába és tanulj meg kódokkal robbantgatni
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: games
technologies: python
site_areas: jam
hardware: ''
software: python
version: 4
last_tested: 2017-01-01
steps: 
-
title: Bevezetés
-
title: Amire szükséged lesz
-
title: Lépj be a Minecraft világába
-
title: Irányítsd a Minecraftot a Pythonnal
-
title: TNT