---
title: Minecraft TNT
hero_image: images / banner.png
description: Utazz a Minecraft Pi világába és tanulj meg kódokkal robbantgatni
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-21
steps:
  - 
    title: Bevezetés
  - 
    title: Lépj be a Minecraft világába
  - 
    title: Irányítsd a Minecraftot a Pythonnal
  - 
    title: TNT
