---
title: Controllare Minecraft con Python
hero_image: images/banner.png
description: 'Naviga nel mondo di Minecraft: Pi, impara a creare con i codici e fai esplodere le cose con il TNT'
listed: false
copyedit: false
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Introduzione
  - 
    title: Di cosa avrai bisogno
  - 
    title: Entra nel mondo di Minecraft
  - 
    title: Controllare Minecraft con Python
